export const TEST_CONFIG = {
    answerOptions: [
        { id: 1, text: "Strongly disagree", score: 1 },
        { id: 2, text: "Disagree", score: 2 },
        { id: 3, text: "Neutral", score: 3 },
        { id: 4, text: "Agree", score: 4 },
        { id: 5, text: "Strongly agree", score: 5 },
    ],
    // The "Relationship MRI" Question Bank (32 Questions)
    questions: [
        // --- DIMENSION 1: COMMUNICATION (Styles) ---
        {
            id: 1,
            text: "When my partner is silent, I panic and think they are pulling away from me.",
            dimension: "communication",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 2,
            text: "During a fight, my partner tends to 'shut down' or walk away.",
            dimension: "communication",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 3,
            text: "I feel a strong, urgent need to resolve our arguments immediately.",
            dimension: "communication",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 4,
            text: "We often have the same exact argument over and over again.",
            dimension: "communication",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 5,
            text: "My partner avoids difficult conversations/conflict to keep the peace.",
            dimension: "communication",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 6,
            text: "I can handle unresolved tension without falling apart.",
            dimension: "communication",
            type: "SL",
            isReverseCoded: true,
        },

        // --- DIMENSION 2: EMOTIONAL SAFETY (Bond/Trust) ---
        {
            id: 7,
            text: "I barely feel 'heard' or understood by my partner.",
            dimension: "emotional_safety",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 8,
            text: "When my partner hurts me, I sometimes feel they did it on purpose.",
            dimension: "emotional_safety",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 9,
            text: "I need frequent reassurance (words of affirmation) to feel safe.",
            dimension: "emotional_safety",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 10,
            text: "I often replay our conversations in my head, analyzing what went wrong.",
            dimension: "emotional_safety",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 11,
            text: "I generally assume my partner has my best interests at heart.",
            dimension: "emotional_safety",
            type: "PM",
            isReverseCoded: true,
        },
        {
            id: 12,
            text: "It takes us a long time to reconnect after a fight.",
            dimension: "emotional_safety",
            type: "PM",
            isReverseCoded: false,
        },

        // --- DIMENSION 3: PHYSICAL INTIMACY (Spark/Sex) ---
        {
            id: 13,
            text: "I feel we have become more like roommates than lovers.",
            dimension: "physical_intimacy",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 14,
            text: "I feel rejected as a person when my partner turns down sex.",
            dimension: "physical_intimacy",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 15,
            text: "I need to feel emotionally close *before* I can get physically close.",
            dimension: "physical_intimacy",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 16,
            text: "One of us wants sex significantly more than the other (mismatched desire).",
            dimension: "physical_intimacy",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 17,
            text: "I sometimes agree to sex just to keep the peace.",
            dimension: "physical_intimacy",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 18,
            text: "We touch affectionately (hugs, holding hands) often, even without sex.",
            dimension: "physical_intimacy",
            type: "PM",
            isReverseCoded: true,
        },

        // --- DIMENSION 4: PRIORITIES & FAIRNESS (Power) ---
        {
            id: 19,
            text: "I carry the 'mental load' (remembering schedules, planning) for our household.",
            dimension: "power_fairness",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 20,
            text: "I often feel like I am my partner's parent or manager.",
            dimension: "power_fairness",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 21,
            text: "Disagreements about money/spending make me feel unsafe.",
            dimension: "power_fairness",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 22,
            text: "I feel my partner doesn't truly understand how much I do for us.",
            dimension: "power_fairness",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 23,
            text: "I feel guilty when I rest, while my partner seems to relax easily.",
            dimension: "power_fairness",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 24,
            text: "We share decisions equally; neither of us dominates.",
            dimension: "power_fairness",
            type: "PM",
            isReverseCoded: true,
        },

        // --- DIMENSION 5: FUTURE & VALUES (Vision) ---
        {
            id: 25,
            text: "I worry that we are growing in different directions.",
            dimension: "future_values",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 26,
            text: "I feel my partner prioritizes their parents/family over me.",
            dimension: "future_values",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 27,
            text: "We rarely 'dream' or purely have fun together anymore.",
            dimension: "future_values",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 28,
            text: "Our life goals (kids, career, lifestyle) feel very aligned.",
            dimension: "future_values",
            type: "PM",
            isReverseCoded: true,
        },
    ],
};
