export const TEST_CONFIG = {
    answerOptions: [
        { id: 1, text: "Strongly disagree", score: 1 },
        { id: 2, text: "Disagree", score: 2 },
        { id: 3, text: "Neutral", score: 3 },
        { id: 4, text: "Agree", score: 4 },
        { id: 5, text: "Strongly agree", score: 5 },
    ],
    questions: [
        // Area A – Silence & Distance
        {
            id: 1,
            text: "When my partner is silent, I think they are pulling away.",
            dimension: "silence_distance",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 2,
            text: "When my partner needs time alone, I see it as a way to process.",
            dimension: "silence_distance",
            type: "PM",
            isReverseCoded: true,
        },
        {
            id: 3,
            text: "If my partner is not clear, I assume something is wrong.",
            dimension: "silence_distance",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 4,
            text: "Silence in a relationship makes me uncomfortable.",
            dimension: "silence_distance",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 5,
            text: "I need verbal reassurance to feel emotionally safe.",
            dimension: "silence_distance",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 6,
            text: "I can give space without needing explanations.",
            dimension: "silence_distance",
            type: "SL",
            isReverseCoded: true,
        },

        // Area B – Conflict
        {
            id: 7,
            text: "During conflict, my partner tends to shut down.",
            dimension: "conflict_tension",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 8,
            text: "My partner avoids difficult conversations.",
            dimension: "conflict_tension",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 9,
            text: "My partner stays emotionally present during disagreements.",
            dimension: "conflict_tension",
            type: "PM",
            isReverseCoded: true,
        },
        {
            id: 10,
            text: "Conflict makes me anxious even when it is small.",
            dimension: "conflict_tension",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 11,
            text: "I feel a strong need to solve problems immediately.",
            dimension: "conflict_tension",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 12,
            text: "I can tolerate unresolved tension for a while.",
            dimension: "conflict_tension",
            type: "SL",
            isReverseCoded: true,
        },

        // Area C – Intentions
        {
            id: 13,
            text: "When my partner hurts me, I think it is intentional.",
            dimension: "intentions",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 14,
            text: "I generally assume my partner has good intentions.",
            dimension: "intentions",
            type: "PM",
            isReverseCoded: true,
        },
        {
            id: 15,
            text: "When I am disappointed, I question my partner’s priorities.",
            dimension: "intentions",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 16,
            text: "I overthink my partner’s behavior.",
            dimension: "intentions",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 17,
            text: "I replay conversations in my head afterward.",
            dimension: "intentions",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 18,
            text: "When something is clarified, I can let it go.",
            dimension: "intentions",
            type: "SL",
            isReverseCoded: true,
        },

        // Area D – Affection & Reassurance
        {
            id: 19,
            text: "My partner shows love more through actions than words.",
            dimension: "reassurance",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 20,
            text: "My partner expresses affection in subtle ways.",
            dimension: "reassurance",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 21,
            text: "I often don’t understand how my partner shows love.",
            dimension: "reassurance",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 22,
            text: "I need frequent emotional reassurance.",
            dimension: "reassurance",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 23,
            text: "I feel valued when affection is clearly expressed.",
            dimension: "reassurance",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 24,
            text: "I don’t need much reassurance to feel secure.",
            dimension: "reassurance",
            type: "SL",
            isReverseCoded: true,
        },

        // Area E – Repair & Closure
        {
            id: 25,
            text: "After conflict, my partner expects things to return to normal quickly.",
            dimension: "repair",
            type: "PM",
            isReverseCoded: false,
        },
        {
            id: 26,
            text: "I need clear emotional repair after conflict.",
            dimension: "repair",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 27,
            text: "I struggle to reconnect if things feel unresolved.",
            dimension: "repair",
            type: "SL",
            isReverseCoded: false,
        },
        {
            id: 28,
            text: "I can reconnect even without verbal closure.",
            dimension: "repair",
            type: "SL",
            isReverseCoded: true,
        },
    ],
};
